apiVersion: v1
kind: Service
metadata:
  name: infra-deployment-example
  namespace: infra-deployment-example
spec:
  ports:
    -   name: http
        port: 8080
        protocol: TCP
        targetPort: 8080
  selector:
    name: infra-deployment-example
    branch: dev
  type: ClusterIP
